### ISSUE TITLE
Needs Explicit License

### ISSUE THREAD

**Issue by Symbolics** [ruricolist/horner#3]
Many people working in a commercial environment need to have an explicit license statement. Generally, most of the BSD and MIT derivatives are allowed. I personally use Boost, and Apache is also quite popular. One form of license that is expressly _disallowed_ in commercial environments is anything GNU.

Will you consider adding an explicit, non-GNU, license to this repository? This Horner library is exactly what I need for a current project.

**Comment by ruricolist** [comment]
Not a problem.
